from PyQt5 import QtCore, QtGui, QtWidgets  
 
# Rent A Car Tracking System by:
# Alp Dogu Akis,
# Doga Bengu Kotan,
# Cisem Gure,
# Yigitcan Teke
class Ui_MainWindow(object):  
    def setupUi(self, MainWindow):  
        MainWindow.setObjectName("MainWindow")  
        MainWindow.resize(1280, 820)  
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, 
QtWidgets.QSizePolicy.Fixed)  
        sizePolicy.setHorizontalStretch(0)  
        sizePolicy.setVerticalStretch(0)  
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())  
        MainWindow.setSizePolicy(sizePolicy)  
        font = QtGui.QFont()  
        font.setFamily("Arial")
        font.setPointSize(12)  
        font.setBold(True)  
        font.setWeight(75)  
        MainWindow.setFont(font)  
        self.centralwidget = QtWidgets.QWidget(MainWindow)  
        self.centralwidget.setObjectName("centralwidget")  
        self.label = QtWidgets.QLabel(self.centralwidget)  
        self.label.setGeometry(QtCore.QRect(30, 10, 261, 31))  
        font = QtGui.QFont()  
        font.setFamily("Arial")
        font.setPointSize(28)  
        self.label.setFont(font)  
        self.label.setStyleSheet("font -size:28pt; font -type:Gotham;")  
        self.label.setObjectName("label")  
        self.label_2 = QtWidgets.QLabel(self.centralwidget)  
        self.label_2.setGeometry(QtCore.QRect(50, 40, 201, 31))  
        font = QtGui.QFont()  
        font.setFamily("Arial")
        font.setPointSize(18)  
        self.label_2.setFont(font)  
        self.label_2.setStyleSheet("font -size:18pt; \n" "")
        self.label_2.setObjectName("label_2")  
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)  
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1261, 701))  
        self.tabWidget.setObjectName("tabWidget")  
        self.tab = QtWidgets.QWidget()  
        self.tab.setObjectName("tab")  
        self.ekle = QtWidgets.QPushButton(self.tab)  
        self.ekle.setGeometry(QtCore.QRect(1140, 10, 101, 71))  
        self.ekle.setObjectName("ekle")  
        self.label_3 = QtWidgets.QLabel(self.tab)  
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 21))  
        self.label_3.setObjectName("label_3")  
        self.salescustomer = QtWidgets.QComboBox(self.tab)  
        self.salescustomer.setGeometry(QtCore.QRect(90, 10, 151, 22))  
        self.salescustomer.setStyleSheet("font -size:9pt;")  
        self.salescustomer.setObjectName("salescustomer")  
        self.label_4 = QtWidgets.QLabel(self.tab)  
        self.label_4.setGeometry(QtCore.QRect(260, 10, 81, 21))  
        self.label_4.setObjectName("label_4")  
        self.salesvehicle = QtWidgets.QComboBox(self.tab)  
        self.salesvehicle.setGeometry(QtCore.QRect(320, 10, 151, 22))  
        self.salesvehicle.setStyleSheet("font -size:9pt;")  
        self.salesvehicle.setObjectName("salesvehicle")  
        self.salesemployee = QtWidgets.QComboBox(self.tab)  
        self.salesemployee.setGeometry(QtCore.QRect(570, 10, 151, 22))  
        self.salesemployee.setStyleSheet("font -size:9pt;")  
        self.salesemployee.setObjectName("salesemployee")  
        self.label_5 = QtWidgets.QLabel(self.tab)  
        self.label_5.setGeometry(QtCore.QRect(490, 10, 81, 21))  
        self.label_5.setObjectName("label_5")  
        self.salesbranch = QtWidgets.QComboBox(self.tab)  
        self.salesbranch.setGeometry(QtCore.QRect(800, 10, 151, 22))  
        self.salesbranch.setStyleSheet("font -size:9pt;")  
        self.salesbranch.setObjectName("salesbranch")  
        self.label_6 = QtWidgets.QLabel(self.tab)  
        self.label_6.setGeometry(QtCore.QRect(740, 10, 81, 21))  
        self.label_6.setObjectName("label_6")  
        self.label_7 = QtWidgets.QLabel(self.tab)  
        self.label_7.setGeometry(QtCore.QRect(970, 30, 81, 21))  
        self.label_7.setObjectName("label_7")  
        self.label_8 = QtWidgets.QLabel(self.tab)  
        self.label_8.setGeometry(QtCore.QRect(50, 50, 81, 21))  
        self.label_8.setObjectName("label_8")  
        self.salescost = QtWidgets.QLineEdit(self.tab)  
        self.salescost.setGeometry(QtCore.QRect(90, 50, 151, 20))  
        self.salescost.setText("")  
        self.salescost.setObjectName("salescost")  
        self.label_15 = QtWidgets.QLabel(self.tab)  
        self.label_15.setGeometry(QtCore.QRect(270, 50, 81, 21))  
        self.label_15.setObjectName("label_15")  
        self.salesprofit = QtWidgets.QLineEdit(self.tab)  
        self.salesprofit.setGeometry(QtCore.QRect(320, 50, 151, 20))  
        self.salesprofit.setText("")  
        self.salesprofit.setObjectName("salesprofit")  
        self.salesstartdate = QtWidgets.QLineEdit(self.tab)  
        self.salesstartdate.setGeometry(QtCore.QRect(570, 50, 151, 20))  
        self.salesstartdate.setText("")  
        self.salesstartdate.setObjectName("salesstartdate")  
        self.label_16 = QtWidgets.QLabel(self.tab)  
        self.label_16.setGeometry(QtCore.QRect(490, 50, 81, 21))  
        self.label_16.setObjectName("label_16")  
        self.label_17 = QtWidgets.QLabel(self.tab)  
        self.label_17.setGeometry(QtCore.QRect(730, 50, 81, 21))  
        self.label_17.setObjectName("label_17")  
        self.salesenddate = QtWidgets.QLineEdit(self.tab)  
        self.salesenddate.setGeometry(QtCore.QRect(800, 50, 151, 20))  
        self.salesenddate.setText("")  
        self.salesenddate.setObjectName("salesenddate")  
        self.tableWidget = QtWidgets.QTableWidget(self.tab)  
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 1231, 531))  
        self.tableWidget.setMaximumSize(QtCore.QSize(1231, 16777215))  
        self.tableWidget.setObjectName("tableWidget")  
        self.tableWidget.setColumnCount(10)  
        self.tableWidget.setRowCount(0)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(0, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(1, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(2, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(3, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(4, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(5, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(6, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(7, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(8, item)  
        item = QtWidgets.QTableWidgetItem()  
        self.tableWidget.setHorizontalHeaderItem(9, item)  
        self.comboBox = QtWidgets.QComboBox(self.tab)  
        self.comboBox.setGeometry(QtCore.QRect(1010, 30, 111, 22))  
        self.comboBox.setObjectName("comboBox")  
        self.comboBox.addItem("")  
        self.comboBox.addItem("")  
        self.salesMesage = QtWidgets.QLabel(self.tab)  
        self.salesMesage.setEnabled(True)  
        self.salesMesage.setGeometry(QtCore.QRect(20, 80, 931, 20))  
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, 
QtWidgets.QSizePolicy.Fixed)  
        sizePolicy.setHorizontalStretch(0)  
        sizePolicy.setVerticalStretch(0)  
        
        sizePolicy.setHeightForWidth(self.salesMesage.sizePolicy().hasHeightForWidth())
        self.salesMesage.setSizePolicy(sizePolicy)  
        self.salesMesage.setText("")  
        self.salesMesage.setObjectName("salesMesage")  
        self.tabWidget.addTab(self.tab, "")  
        self.tab_5 = QtWidgets.QWidget()  
        self.tab_5.setObjectName("tab_5")  
        self.register_2 = QtWidgets.QPushButton(self.tab_5)  
        self.register_2.setGeometry(QtCore.QRect(490, 540, 341, 51))  
        self.register_2.setObjectName("register_2")  
        self.label_27 = QtWidgets.QLabel(self.tab_5)  
        self.label_27.setGeometry(QtCore.QRect(190, 210, 241, 41))  
        self.label_27.setStyleSheet("font -size:24pt;")  
        self.label_27.setObjectName("label_27")  
        self.cName = QtWidgets.QLineEdit(self.tab_5)  
        self.cName.setGeometry(QtCore.QRect(440, 220, 441, 31))  
        self.cName.setObjectName("cName")  
        self.cSurname = QtWidgets.QLineEdit(self.tab_5)  
        self.cSurname.setGeometry(QtCore.QRect(440, 270, 441, 31))  
        self.cSurname.setText("")  
        self.cSurname.setObjectName("cSurname")  
        self.label_28 = QtWidgets.QLabel(self.tab_5)  
        self.label_28.setGeometry(QtCore.QRect(150, 260, 311, 41))  
        self.label_28.setStyleSheet("font -size:24pt;")  
        self.label_28.setObjectName("label_28")  
        self.cPhone = QtWidgets.QLineEdit(self.tab_5)  
        self.cPhone.setGeometry(QtCore.QRect(440, 320, 441, 31))  
        self.cPhone.setText("")  
        self.cPhone.setObjectName("cPhone")  
        self.label_29 = QtWidgets.QLabel(self.tab_5)  
        self.label_29.setGeometry(QtCore.QRect(180, 310, 311, 41))  
        self.label_29.setStyleSheet("font -size:24pt;")  
        self.label_29.setObjectName("label_29")  
        self.cEmail = QtWidgets.QLineEdit(self.tab_5)  
        self.cEmail.setGeometry(QtCore.QRect(440, 370, 441, 31))  
        self.cEmail.setText("")  
        self.cEmail.setObjectName("cEmail")  
        self.label_30 = QtWidgets.QLabel(self.tab_5)  
        self.label_30.setGeometry(QtCore.QRect(190, 360, 311, 41))  
        self.label_30.setStyleSheet("font -size:24pt;")  
        self.label_30.setObjectName("label_30")  
        self.cGender = QtWidgets.QComboBox(self.tab_5)  
        self.cGender.setGeometry(QtCore.QRect(440, 420, 441, 31))  
        self.cGender.setObjectName("cGender")  
        self.cGender.addItem("")  
        self.cGender.addItem("")  
        self.cGender.addItem("")  
        self.label_31 = QtWidgets.QLabel(self.tab_5)  
        self.label_31.setGeometry(QtCore.QRect(170, 410, 311, 41))  
        self.label_31.setStyleSheet("font -size:24pt;")  
        self.label_31.setObjectName("label_31")  
        self.label_35 = QtWidgets.QLabel(self.tab_5)  
        self.label_35.setGeometry(QtCore.QRect(510, 60, 291, 111))  
        self.label_35.setStyleSheet("font -size:28pt; \n" "")
        self.label_35.setObjectName("label_35")  
        self.cMesage = QtWidgets.QLabel(self.tab_5)  
        self.cMesage.setGeometry(QtCore.QRect(450, 470, 431, 31))  
        self.cMesage.setText("")  
        self.cMesage.setObjectName("cMesage")  
        self.tabWidget.addTab(self.tab_5, "")  
        self.tab_2 = QtWidgets.QWidget()  
        self.tab_2.setObjectName("tab_2")  
        self.tabWidget.addTab(self.tab_2, "")  
        self.tabWidget.raise_()  
        self.label.raise_()  
        self.label_2.raise_()  
        MainWindow.setCentralWidget(self.centralwidget)  
        self.menubar = QtWidgets.QMenuBar(MainWindow)  
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 27))  
        self.menubar.setObjectName("menubar")  
        self.menuTPS = QtWidgets.QMenu(self.menubar)  
        self.menuTPS.setObjectName("menuTPS")  
        MainWindow.setMenuBar(self.menubar)  
        self.statusbar = QtWidgets.QStatusBar(MainWindow)  
        self.statusbar.setObjectName("statusbar")  
        MainWindow.setStatusBar(self.statusbar)  
        self.menubar.addAction(self.menuTPS.menuAction())  
 
        self.retranslateUi(MainWindow)  
        self.tabWidget.setCurrentIndex(0)  
        QtCore.QMetaObject.connectSlotsByName(MainWindow)  
 
    def retranslateUi(self, MainWindow):  
        _translate = QtCore.QCoreApplication.translate  
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))  
        self.label.setText(_translate("MainWindow", "RENT A CAR"))  
        self.label_2.setText(_translate("MainWindow", "TPS PROGRAM"))  
        self.ekle.setText(_translate("MainWindow", "ADD"))  
        self.label_3.setText(_translate("MainWindow", "Customer:"))  
        self.label_4.setText(_translate("MainWindow", "Vehicle:"))  
        self.label_5.setText(_translate("MainWindow", "Employee:"))  
        self.label_6.setText(_translate("MainWindow", "Branch:"))  
        self.label_7.setText(_translate("MainWindow", "Type:"))  
        self.label_8.setText(_translate("MainWindow", "Cost:"))  
        self.label_15.setText(_translate("MainWindow", "Profit:"))  
        self.label_16.setText(_translate("MainWindow", "Start Date:"))  
        self.label_17.setText(_translate("MainWindow", "End Date:"))  
        item = self.tableWidget.horizontalHeaderItem(0)  
        item.setText(_translate("MainWindow", "SalesID"))  
        item = self.tableWidget.horizontalHeaderItem(1)  
        item.setText(_translate("MainWindow", "Customer"))
        item = self.tableWidget.horizontalHeaderItem(2)  
        item.setText(_translate("MainWindow", "Vehicle"))  
        item = self.tableWidget.horizontalHeaderItem(3)  
        item.setText(_translate("MainWindow", "Employee"))
        item = self.tableWidget.horizontalHeaderItem(4)  
        item.setText(_translate("MainWindow", "Branch"))
        item = self.tableWidget.horizontalHeaderItem(5)  
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.tableWidget.horizontalHeaderItem(6)  
        item.setText(_translate("MainWindow", "End Date"))
        item = self.tableWidget.horizontalHeaderItem(7)  
        item.setText(_translate("MainWindow", "Sale Type"))
        item = self.tableWidget.horizontalHeaderItem(8)  
        item.setText(_translate("MainWindow", "Sale Cost"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Sale Profit"))


        self.comboBox.setItemText(0, _translate("MainWindow", "Bireysel"))  
        self.comboBox.setItemText(1, _translate("MainWindow", "Kurumsal"))  
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "ENTER SALES"))
        self.register_2.setText(_translate("MainWindow", "REGISTER"))  
        self.label_27.setText(_translate("MainWindow", "Customer Name:"))  
        self.label_28.setText(_translate("MainWindow", "Customer Surname:"))  
        self.label_29.setText(_translate("MainWindow", "Customer Phone:"))  
        self.label_30.setText(_translate("MainWindow", "Customer Email:"))  
        self.cGender.setItemText(0, _translate("MainWindow", "Select"))  
        self.cGender.setItemText(1, _translate("MainWindow", "Kadin"))  
        self.cGender.setItemText(2, _translate("MainWindow", "Erkek"))  
        self.label_31.setText(_translate("MainWindow", "Customer Gender:"))  
        self.label_35.setText(_translate("MainWindow", "NEW CUSTOMER"))  
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "CUSTOMER REGISTER"))
        self.menuTPS.setTitle(_translate("MainWindow", "TPS"))  
 
 
if __name__ == "__main__":  
    import sys  
    app = QtWidgets.QApplication(sys.argv)  
    MainWindow = QtWidgets.QMainWindow()  
    ui = Ui_MainWindow()  
    ui.setupUi(MainWindow)  
    MainWindow.show()  
    sys.exit(app.exec_())  
